### ISSUE TITLE
file does not open

### ISSUE THREAD

**Issue by myrmoteras** [plazi/polish-biodiversity-literature#3]
this polish article does not open. Is it closed?

[115-118_Ambroziak.pdf](https://github.com/plazi/polish-biodiversity-literature/files/4201724/115-118_Ambroziak.pdf)

**Comment by gsautter** [comment]
Nope ... just some weird syntax oddity that the parser wasn't prepared to handle ... added a catch now, comes with next build.

Here's the IMF (just remove the `.zip` extension, had to add it so GitHub accepts the file): [115-118_Ambroziak.pdf.imf.zip](https://github.com/plazi/polish-biodiversity-literature/files/4204119/115-118_Ambroziak.pdf.imf.zip)
